<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLs4ATny\srcApp_KernelAppDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLs4ATny/srcApp_KernelAppDebugContainer.php') {
    touch(__DIR__.'/ContainerLs4ATny.legacy');

    return;
}

if (!\class_exists(srcApp_KernelAppDebugContainer::class, false)) {
    \class_alias(\ContainerLs4ATny\srcApp_KernelAppDebugContainer::class, srcApp_KernelAppDebugContainer::class, false);
}

return new \ContainerLs4ATny\srcApp_KernelAppDebugContainer([
    'container.build_hash' => 'Ls4ATny',
    'container.build_id' => '9a1fc0f7',
    'container.build_time' => 1569569746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLs4ATny');
