<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'projet' => [['id'], ['_controller' => 'App\\Controller\\MainController::projet'], ['id' => '[0-9]'], [['variable', '/', '[0-9]', 'id', true], ['text', '/projet']], [], []],
];
