<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/bootstrap' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/bootstrap~js/chat~js/jquery.js',
                '/build/vendors~js/bootstrap~js/chat.js',
                '/build/vendors~js/bootstrap.js',
                '/build/js/bootstrap.js',
            ],
        ],
        'js/jquery' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/bootstrap~js/chat~js/jquery.js',
                '/build/js/jquery.js',
            ],
        ],
        'js/chat' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~js/bootstrap~js/chat~js/jquery.js',
                '/build/vendors~js/bootstrap~js/chat.js',
                '/build/js/chat.js',
            ],
        ],
        'css/reset' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/css/reset.css',
            ],
        ],
        'css/style' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/css/style.css',
            ],
        ],
        'css/projet' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/css/projet.css',
            ],
        ],
        'css/bootstrap' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/css/bootstrap.css',
            ],
        ],
    ],
],

]];
