<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4fIHW5f' shared service.

return $this->privates['.service_locator.4fIHW5f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'message' => ['privates', '.errored..service_locator.4fIHW5f.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.4fIHW5f": it references class "App\\Entity\\Message" but no such service exists.'],
], [
    'manager' => '?',
    'message' => 'App\\Entity\\Message',
]);
