<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WXYuUMD' shared service.

return $this->privates['.service_locator.WXYuUMD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repomessage' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService.php', true],
], [
    'repomessage' => 'App\\Repository\\MessageRepository',
]);
