<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fdSP.1g' shared service.

return $this->privates['.service_locator.fdSP.1g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repocommentaire' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService.php', true],
    'repoprojet' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService.php', true],
], [
    'manager' => '?',
    'repocommentaire' => 'App\\Repository\\CommentaireRepository',
    'repoprojet' => 'App\\Repository\\ProjetRepository',
]);
