<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dwBiYQ1' shared service.

return $this->privates['.service_locator.dwBiYQ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repoplat' => ['privates', 'App\\Repository\\PlatsRepository', 'getPlatsRepositoryService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
], [
    'repoplat' => 'App\\Repository\\PlatsRepository',
    'session' => '?',
]);
