<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T5ZUgUW' shared service.

return $this->privates['.service_locator.T5ZUgUW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::index' => ['privates', '.service_locator.7BobChD', 'get_ServiceLocator_7BobChDService.php', true],
    'App\\Controller\\MainController::projet' => ['privates', '.service_locator.7BobChD', 'get_ServiceLocator_7BobChDService.php', true],
    'App\\Controller\\MainController:index' => ['privates', '.service_locator.7BobChD', 'get_ServiceLocator_7BobChDService.php', true],
    'App\\Controller\\MainController:projet' => ['privates', '.service_locator.7BobChD', 'get_ServiceLocator_7BobChDService.php', true],
], [
    'App\\Controller\\MainController::index' => '?',
    'App\\Controller\\MainController::projet' => '?',
    'App\\Controller\\MainController:index' => '?',
    'App\\Controller\\MainController:projet' => '?',
]);
