<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQDsw0Ry\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQDsw0Ry/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQDsw0Ry.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQDsw0Ry\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQDsw0Ry\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QDsw0Ry',
    'container.build_id' => 'da2d0948',
    'container.build_time' => 1573074134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQDsw0Ry');
