<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'css/style' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/style.d569049f.css',
            ],
        ],
        'js/bootstrap' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/1.37e3237e.js',
                '/build/js/bootstrap.a3b58c5c.js',
            ],
        ],
        'js/chat' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/1.37e3237e.js',
                '/build/js/chat.780335c9.js',
            ],
        ],
        'js/projet' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/js/projet.a0318040.js',
            ],
        ],
        'js/flexslider' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/1.37e3237e.js',
                '/build/js/flexslider.7da5459c.js',
            ],
        ],
        'js/marashome' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/2.32caca46.js',
                '/build/js/marashome.3f658a09.js',
            ],
        ],
        'css/reset' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/reset.ba902a9a.css',
            ],
        ],
        'js/jquery' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
                '/build/0.493adf10.js',
                '/build/js/jquery.02d5b7af.js',
            ],
        ],
        'css/projet' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/projet.b64a86d6.css',
            ],
        ],
        'css/bootstrap' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/bootstrap.82a4e5e0.css',
            ],
        ],
        'css/cvstyle' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/cvstyle.195783c9.css',
            ],
        ],
        'css/flexslider' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/flexslider.c4cba1c1.css',
            ],
        ],
        'css/marashome' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/marashome.c8dd3c90.css',
            ],
        ],
        'css/marasplat' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/marasplat.2ce6cdc0.css',
            ],
        ],
        'css/maraspanier' => [
            'js' => [
                '/build/runtime.f1cd8733.js',
            ],
            'css' => [
                '/build/css/maraspanier.b10736b4.css',
            ],
        ],
    ],
],

]];
